name: Lint GitHub Actions
on:
  push:
    branches:
      - main
    paths: ['.github/**']
  pull_request:
    paths: ['.github/**']

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false
      - uses: alphagov/govuk-infrastructure/.github/actions/actionlint@main
